

import type { Project } from '@/lib/types';
import { paymentData } from '@/lib/payment-data';

const shiftAvailability = [
  { unit: '1501', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1502', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1503', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1504', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1505', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1506', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1507', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1508', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1509', type: 'Studio', area: 24.5, status: 'Consulte Disponibilidade' },
  { unit: '1401', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1402', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1403', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1404', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1405', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1406', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1407', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1408', type: 'Studio', area: 108, status: 'Consulte Disponibilidade' },
  { unit: '1409', type: 'Studio', area: 34.18, status: 'Consulte Disponibilidade' },
  { unit: '1301', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1302', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1303', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1304', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1305', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1306', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1307', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1308', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1309', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1310', type: 'Studio', area: 91.63, status: 'Consulte Disponibilidade' },
  { unit: '1201', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1202', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1203', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1204', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1205', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1206', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1207', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1208', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1209', type: 'Studio', area: 74.7, status: 'Consulte Disponibilidade' },
  { unit: '1210', type: 'Studio', area: 33.7, status: 'Consulte Disponibilidade' },
  { unit: '1211', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1101', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1102', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1103', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1104', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1105', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1106', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1107', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1108', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1109', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1110', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '1111', type: 'Studio', area: 30.13, status: 'Consulte Disponibilidade' },
  { unit: '1112', type: 'Studio', area: 81.22, status: 'Consulte Disponibilidade' },
  { unit: '1001', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1002', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1003', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '1004', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '1005', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '1006', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1007', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1008', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1009', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1010', type: 'Studio', area: 76.37, status: 'Consulte Disponibilidade' },
  { unit: '1011', type: 'Studio', area: 33.53, status: 'Consulte Disponibilidade' },
  { unit: '1012', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '1013', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '901', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '902', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '903', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '904', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '905', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '906', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '907', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '908', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '909', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '910', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '911', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '912', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '913', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '914', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '915', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '801', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '802', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '803', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '804', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '805', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '806', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '807', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '808', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '809', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '810', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '811', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '812', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '813', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '814', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '815', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '701', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '702', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '703', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '704', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '705', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '706', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '707', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '708', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '709', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '710', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '711', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '712', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '713', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '714', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '715', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '601', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '602', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '603', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '604', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '605', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '606', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '607', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '608', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '609', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '610', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '611', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '612', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '613', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '614', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '615', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '501', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '502', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '503', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '504', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '505', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '506', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '507', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '508', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '509', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '510', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '511', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '512', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '513', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '514', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '515', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '401', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '402', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '403', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '404', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '405', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '406', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '407', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '408', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '409', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '410', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '411', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '412', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '413', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '414', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '415', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '301', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '302', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '303', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '304', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '305', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '306', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '307', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '308', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '309', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '310', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '311', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '312', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '313', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '314', type: 'Studio', area: 23.75, status: 'Consulte Disponibilidade' },
  { unit: '315', type: 'Studio', area: 24.28, status: 'Consulte Disponibilidade' },
  { unit: '201', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '202', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '203', type: 'Studio', area: 23.66, status: 'Consulte Disponibilidade' },
  { unit: '204', type: 'Studio', area: 24.38, status: 'Consulte Disponibilidade' },
  { unit: '205', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '206', type: 'Studio', area: 25.42, status: 'Consulte Disponibilidade' },
  { unit: '207', type: 'Studio', area: 25.42, status: 'Consulte Disponibilidade' },
  { unit: '208', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '209', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '210', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '211', type: 'Studio', area: 25.48, status: 'Consulte Disponibilidade' },
  { unit: '212', type: 'Studio', area: 25.78, status: 'Consulte Disponibilidade' },
  { unit: '213', type: 'Studio', area: 47.52, status: 'Consulte Disponibilidade' },
  { unit: '214', type: 'Studio', area: 46.48, status: 'Consulte Disponibilidade' },
  { unit: '215', type: 'Studio', area: 47.34, status: 'Consulte Disponibilidade' },
].map(u => ({
  ...u, 
  type: u.area > 40 ? 'Apartamento' : 'Studio',
  paymentFlow: paymentData[u.unit]
})) as any[];


export const projects: Project[] = [
  // Plaenge
  {
    id: 1,
    name: 'ORBITALE',
    brand: 'Plaenge',
    slug: 'orbitale',
    description:
      'Um marco arquitetônico que redefine o horizonte da cidade. ORBITALE combina design futurista com conforto e sofisticação, oferecendo uma experiência de vida única e vistas panorâmicas espetaculares.',
    heroImageId: 'orbitale-hero',
    galleryImageIds: ['orbitale-gal-1', 'orbitale-gal-2', 'orbitale-gal-3', 'orbitale-gal-4'],
    floorPlanImageIds: ['orbitale-plan-1', 'orbitale-plan-2'],
    location: {
      address: 'Av. do Futuro, 123, Centro, Metrópole',
      mapImageId: 'map-placeholder',
    },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    availability: [
      { unit: '101', type: '2 Quartos', area: 120, status: 'Vendido' },
      { unit: '102', type: '2 Quartos', area: 125, status: 'Disponível' },
      { unit: '201', type: '3 Quartos', area: 180, status: 'Disponível' },
      { unit: 'P-01', type: 'Penthouse', area: 350, status: 'Vendido' },
    ],
  },
  {
    id: 2,
    name: 'EDITION MOINHOS',
    brand: 'Plaenge',
    slug: 'edition-moinhos',
    description:
      'O charme do clássico encontra a funcionalidade do moderno. Localizado no coração do bairro Moinhos, o EDITION oferece exclusividade e elegância em cada detalhe, próximo a tudo que você precisa.',
    heroImageId: 'em-hero',
    galleryImageIds: [
      'em-gal-1',  'em-gal-2',  'em-gal-3',  'em-gal-4',  'em-gal-5',
      'em-gal-6',  'em-gal-7',  'em-gal-8',  'em-gal-9',  'em-gal-10',
      'em-gal-11', 'em-gal-12', 'em-gal-13', 'em-gal-14', 'em-gal-15',
      'em-gal-16', 'em-gal-17', 'em-gal-18', 'em-gal-19', 'em-gal-20',
      'em-gal-21', 'em-gal-22', 'em-gal-23', 'em-gal-24', 'em-gal-25',
      'em-gal-26', 'em-gal-27', 'em-gal-28', 'em-gal-29', 'em-gal-30',
      'em-gal-31'
    ],
    floorPlanImageIds: [
        'em-plan-32', 'em-plan-33', 'em-plan-34', 'em-plan-35', 'em-plan-36'
    ],
    location: {
      address: 'Jardim Cristogel 215',
      mapImageId: 'map-placeholder',
    },
    videoUrl: 'https://www.youtube.com/embed/pkhZo3FDBWE',
    availability: [
      { unit: 'A-3', type: '4 Suítes', area: 250, status: 'Disponível' },
      { unit: 'A-4', type: '4 Suítes', area: 250, status: 'Disponível' },
      { unit: 'B-1', type: 'Garden', area: 320, status: 'Vendido' },
    ],
  },
  {
    id: 3,
    name: 'VERDANT',
    brand: 'Plaenge',
    slug: 'verdant',
    description:
      'Um refúgio verde em meio à cidade. O VERDANT integra natureza e arquitetura de forma harmoniosa, com jardins verticais e espaços que promovem o bem-estar e a conexão com o meio ambiente.',
    heroImageId: 'verdant-hero',
    galleryImageIds: ['verdant-gal-1', 'verdant-gal-2', 'verdant-gal-3', 'verdant-gal-4'],
    floorPlanImageIds: ['verdant-plan-1', 'verdant-plan-2'],
    location: {
      address: 'Alameda das Flores, 789, Jardim Europa, Metrópole',
      mapImageId: 'map-placeholder',
    },
    availability: [
      { unit: 'G-10', type: 'Loft Duplex', area: 150, status: 'Disponível' },
      { unit: 'G-12', type: 'Loft Duplex', area: 150, status: 'Vendido' },
      { unit: 'V-22', type: '2 Quartos', area: 95, status: 'Disponível' },
    ],
  },
  // Vanguard
  {
    id: 4,
    name: 'MOOD CENTRAL PARQUE',
    brand: 'Vanguard',
    slug: 'mood-central-parque',
    description:
      'Vibrante, conectado e cheio de vida. O MOOD está localizado ao lado do Central Parque, ideal para quem busca um estilo de vida dinâmico, com espaços criativos e apartamentos inteligentes.',
    heroImageId: 'mood-hero',
    galleryImageIds: ['mood-gal-1', 'mood-gal-2', 'mood-gal-3', 'mood-gal-4'],
    floorPlanImageIds: ['mood-plan-1'],
    location: {
      address: 'Praça Central, 101, Parque Urbano, Metrópole',
      mapImageId: 'map-placeholder',
    },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    availability: [
      { unit: '505', type: 'Studio', area: 45, status: 'Disponível' },
      { unit: '506', type: 'Studio', area: 45, status: 'Vendido' },
      { unit: '810', type: '1 Quarto', area: 60, status: 'Disponível' },
    ],
  },
  {
    id: 5,
    name: 'WAVE HOME RESORT',
    brand: 'Vanguard',
    slug: 'wave-home-resort',
    description: 'Seu refúgio particular à beira-mar.',
    longDescription: 'O WAVE HOME RESORT foi projetado para quem busca um estilo de vida sofisticado e, ao mesmo tempo, descontraído. Com uma arquitetura moderna que se integra perfeitamente à paisagem litorânea, o empreendimento oferece apartamentos amplos, com varandas generosas e uma vista espetacular para o mar. Aqui, cada detalhe foi pensado para proporcionar o máximo de conforto e bem-estar aos seus moradores.',
    heroImageId: 'aquavista-hero',
    aboutImageId: 'aquavista-about',
    galleryImageIds: ['aquavista-gal-1', 'aquavista-gal-2', 'aquavista-gal-3', 'aquavista-gal-4', 'aquavista-gal-5', 'aquavista-gal-6'],
    floorPlanImageIds: ['aquavista-plan-1', 'aquavista-plan-2'],
    highlights: [
      {
        icon: 'Waves',
        title: 'VISTA PARA O MAR',
        description: 'Todos os apartamentos com vista permanente para o oceano.',
      },
      {
        icon: 'Palmtree',
        title: 'LAZER COMPLETO',
        description: 'Piscina com borda infinita, spa, academia e salão de festas.',
      },
      {
        icon: 'Building2',
        title: 'DESIGN MODERNO',
        description: 'Arquitetura contemporânea que valoriza a luz e a ventilação natural.',
      },
      {
        icon: 'MapPin',
        title: 'LOCALIZAÇÃO PRIVILEGIADA',
        description: 'A poucos passos da praia e próximo a restaurantes e lojas.',
      },
    ],
    location: {
      address: 'Av. Beira Mar, 202, Praia Bela, Litoral',
      mapImageId: 'map-placeholder',
    },
    availability: [
      { unit: 'T1-303', type: '2 Quartos Vista Mar', area: 88, status: 'Disponível' },
      { unit: 'T1-304', type: '2 Quartos Vista Mar', area: 88, status: 'Vendido' },
      { unit: 'T2-501', type: '3 Quartos Vista Mar', area: 115, status: 'Disponível' },
    ],
    theme: {
      primary: '200 80% 30%',
      primaryForeground: '210 40% 98%',
      secondary: '210 40% 96.1%',
      accent: '200 90% 50%',
    },
    contactButtonText: 'FALAR COM UM CONSULTOR',
    contactButtonLink: '#',
  },
  {
    id: 6,
    name: 'YUNA JARDIM BOTÂNICO',
    brand: 'Vanguard',
    slug: 'yuna-jardim-botanico',
    description:
      'Equilíbrio e tranquilidade ao lado do Jardim Botânico. O YUNA foi pensado para quem valoriza a paz e a natureza, oferecendo um ambiente sereno e acolhedor para recarregar as energias.',
    heroImageId: 'yuna-hero',
    galleryImageIds: ['yuna-gal-1', 'yuna-gal-2', 'yuna-gal-3'],
    floorPlanImageIds: ['yuna-plan-1'],
    location: {
      address: 'Rua do Jardim, 303, Jardim Botânico, Metrópole',
      mapImageId: 'map-placeholder',
    },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    availability: [
      { unit: 'L-01', type: '2 Quartos com Jardim', area: 110, status: 'Vendido' },
      { unit: 'L-02', type: '2 Quartos com Jardim', area: 112, status: 'Disponível' },
    ],
  },
  {
    id: 7,
    name: 'TREND DOWNTOWN',
    brand: 'Vanguard',
    slug: 'trend-downtown',
    description:
      'O pulso da cidade ao seu alcance. Com design arrojado e localização estratégica no centro, o TREND é perfeito para quem tem uma vida urbana agitada e não abre mão de praticidade e estilo.',
    heroImageId: 'trend-hero',
    galleryImageIds: ['trend-gal-1', 'trend-gal-2', 'trend-gal-3'],
    floorPlanImageIds: ['trend-plan-1'],
    location: {
      address: 'Rua 24 Horas, 404, Downtown, Metrópole',
      mapImageId: 'map-placeholder',
    },
    availability: [
      { unit: '1501', type: 'Studio+', area: 55, status: 'Disponível' },
      { unit: '1502', type: 'Studio+', area: 55, status: 'Disponível' },
      { unit: '2105', type: '1 Quarto', area: 70, status: 'Vendido' },
    ],
  },
  {
    id: 8,
    name: 'SHIFT',
    brand: 'Vanguard',
    slug: 'shift',
    description:
      'O endereço mais cobiçado de Porto Alegre. Localização absolutamente privilegiada na esquina da Rua Silva Jardim com a Rua 24 de Outubro. Morar no Shift é desfrutar da vibração urbana do Moinhos de Vento, um novo projeto VANGUARD | TGD. O entorno oferece referências gastronômicas como Roister e Leiteria, além do lazer no Parcão. O empreendimento conta com 1 Torre e 184 unidades.',
    heroImageId: 'shift-hero',
    galleryImageIds: [],
    floorPlanImageIds: ['shift-floor-plan-1','shift-floor-plan-2','shift-floor-plan-3','shift-floor-plan-4','shift-floor-plan-5','shift-floor-plan-6','shift-floor-plan-7'],
    bannerImageIds: ['shift-banner-1', 'shift-banner-2', 'shift-banner-3', 'shift-banner-4', 'shift-banner-5'],
    location: {
      address: 'Silva Jardim, 21 (esquina com Rua 24 de Outubro), Moinhos de Vento, Porto Alegre, RS',
      mapImageId: 'map-placeholder',
    },
    videoUrl: 'https://youtu.be/wSoKcCmErg8',
    availability: shiftAvailability,
  },
];

    